name: Create and Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install root and frontend Node.js dependencies
        run: npm install && npm install --prefix frontend

      - name: Install Python dependencies
        run: pip install -r service/requirements.txt

      - name: Download FFmpeg and FFprobe
        shell: bash
        run: |
          mkdir -p bin
          if [ "${{ runner.os }}" == "macOS" ]; then
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffmpeg-mac-arm64 -o bin/ffmpeg
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffprobe-mac-arm64 -o bin/ffprobe
          elif [ "${{ runner.os }}" == "Windows" ]; then
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffmpeg-win32-x64.exe -o bin/ffmpeg.exe
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffprobe-win32-x64.exe -o bin/ffprobe.exe
          fi
          chmod +x bin/ffmpeg*

      - name: Build Electron app (without publishing)
        run: npm run dist

      - name: DEBUG - List files in build directory
        shell: bash
        run: ls -R dist

      - name: Prepare Artifacts for Upload
        id: prep_artifacts
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            ARTIFACT_PATH=$(ls dist/*.dmg)
            ARTIFACT_NAME="YT-Link-macOS-dmg"
          elif [ "${{ runner.os }}" == "Windows" ]; then
            ARTIFACT_PATH=$(ls dist/*.zip)
            ARTIFACT_NAME="YT-Link-Windows-zip"
          fi
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write 
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files for verification
        run: ls -R artifacts

      # This is the new step that fixes the error.
      # It deletes the existing release and tag if they already exist.
      - name: Delete existing release and tag
        uses: dev-drpr/delete-tag-and-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Gets the tag name (e.g., v1.0.0) from the push event
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_tag: true # Ensures the git tag is also removed

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          # The files from the build job will be attached to this new release
          files: |
            artifacts/YT-Link-macOS-dmg/*
            artifacts/YT-Link-Windows-zip/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
