name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    # This section grants the workflow permission to create a release.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r service/requirements.txt

      - name: Install Root and Frontend Dependencies
        run: npm install && npm install --prefix frontend

      - name: Build and Package Application
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename Artifact for Windows
        if: runner.os == 'Windows'
        run: ren dist\*.zip yt-link-windows.zip

      - name: Rename Artifact for macOS
        if: runner.os == 'macOS'
        # This now correctly renames the file inside the dist directory.
        run: mv dist/*.dmg dist/yt-link-macos.dmg

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: yt-link-windows
          path: dist/yt-link-windows.zip

      - name: Upload macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: yt-link-macos
          path: dist/yt-link-macos.dmg
