name: Create and Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # --- Build Job: Creates the app for macOS and Windows ---
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using a modern LTS version of Node.js
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install root and frontend Node.js dependencies
        run: npm install && npm install --prefix frontend

      - name: Install Python dependencies
        run: pip install -r service/requirements.txt

      - name: Download FFmpeg and FFprobe
        shell: bash
        run: |
          mkdir -p bin
          if [ "${{ runner.os }}" == "macOS" ]; then
            # Use the arm64 version for modern macOS runners
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffmpeg-mac-arm64 -o bin/ffmpeg
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffprobe-mac-arm64 -o bin/ffprobe
          elif [ "${{ runner.os }}" == "Windows" ]; then
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffmpeg-win32-x64.exe -o bin/ffmpeg.exe
            curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b4.4/ffprobe-win32-x64.exe -o bin/ffprobe.exe
          fi
          
          # This step is a good failsafe, but our afterPack.js script is the definitive solution
          if [ "${{ runner.os }}" != "Windows" ]; then
            chmod +x bin/*
          fi

      - name: Build Electron app
        # The `npm run dist` command will trigger the scripts in package.json,
        # which in turn runs electron-builder and our `afterPack.js` hook.
        # This hook is the most reliable way to set all necessary permissions.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist

      - name: DEBUG - List files in build directory
        shell: bash
        run: ls -R dist

      - name: Prepare Artifacts for Upload
        id: prep_artifacts
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            ARTIFACT_PATH=$(ls dist/*.dmg)
            ARTIFACT_NAME="YT-Link-macOS-dmg"
          elif [ "${{ runner.os }}" == "Windows" ]; then
            ARTIFACT_PATH=$(ls dist/*.zip)
            ARTIFACT_NAME="YT-Link-Windows-zip"
          fi
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

  # --- Release Job: Creates the final GitHub Release ---
  release:
    runs-on: ubuntu-latest
    needs: build # This job will only run after the build job for both OSes succeeds
    permissions:
      contents: write # This permission is required to create a release
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded files for verification
        run: ls -R artifacts

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          # This glob pattern will find the .dmg and .zip files inside their respective folders
          files: |
            artifacts/YT-Link-macOS-dmg/*
            artifacts/YT-Link-Windows-zip/*
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
