# .github/workflows/release.yml
# This workflow is corrected to combine all frontend build commands into a single,
# robust step. This resolves all pathing and shell issues in the CI environment.

name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'service/**'
      - '.github/workflows/release.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  # Job 1: Build and Package the application for each OS
  build_and_package:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Cache for pip dependencies
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/service/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Cache for frontend node_modules - the path must be explicit.
      - name: Cache frontend node_modules
        id: cache-frontend-npm
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-npm-frontend-${{ hashFiles('**/frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-frontend-
      
      # --- THE DEFINITIVE FINAL FIX ---
      # All frontend commands are combined into a single step with a specified shell
      # and working directory to guarantee correct execution on all platforms.
      - name: Install All Dependencies and Build
        shell: bash
        run: |
          echo "Installing Python dependencies..."
          pip install -r ./service/requirements.txt
          
          echo "Setting up frontend..."
          cd frontend
          
          echo "Removing lockfile for a clean install..."
          rm -f package-lock.json
          
          echo "Installing Node.js dependencies..."
          npm install
          
          echo "Building the frontend..."
          npm run build

      # Run the package script from within the frontend directory
      - name: Run Electron Packager
        working-directory: ./frontend
        run: npm run package
        env:
          # This token is required by electron-builder to fetch dependencies.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # The rest of the steps rename the artifacts for clarity.
      - name: Rename Artifact for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd frontend/dist
          $file = Get-ChildItem -Filter *.exe | Select-Object -First 1
          Rename-Item -Path $file.FullName -NewName "yt-link-windows.exe"
          
      - name: Rename Artifact for macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd frontend/dist
          mv *.dmg yt-link-macos.dmg
          
      - name: Rename Artifact for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd frontend/dist
          mv *.AppImage yt-link-linux.AppImage

      - name: Upload Packaged Application
        uses: actions/upload-artifact@v4
        with:
          name: yt-link-${{ matrix.os }}
          path: frontend/dist/*
          retention-days: 7
