# .github/workflows/release.yml
# This workflow is corrected to properly handle an npm workspace setup.

name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'service/**'
      - '.github/workflows/release.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  # Job 1: Build the platform-independent code
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # For a workspace, we cache the single root node_modules directory
      - name: Cache root node_modules
        id: cache-root-npm
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-root-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-root-

      # Cache for pip dependencies remains the same
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/service/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # *** THE KEY FIX IS HERE ***
      # In an npm workspace, you only need to run npm install from the root.
      # It will automatically install dependencies for all workspaces (frontend, backend).
      - name: Install All Dependencies
        run: |
          npm install
          cd service && pip install -r requirements.txt
      
      # Build the frontend from within its workspace context
      - name: Build Frontend
        run: npm run build --workspace=frontend
      
      # Upload the entire built project to be used by the packaging job
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .
          retention-days: 1

  # Job 2: Package the application for each OS
  package:
    needs: build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
          
      # Run the package script from the frontend workspace context
      - name: Run Electron Packager
        run: npm run package --workspace=frontend
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Rename Artifact for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd frontend/dist
          $file = Get-ChildItem -Filter *.exe | Select-Object -First 1
          Rename-Item -Path $file.FullName -NewName "yt-link-windows.exe"
          
      - name: Rename Artifact for macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd frontend/dist
          mv *.dmg yt-link-macos.dmg
          
      - name: Rename Artifact for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd frontend/dist
          mv *.AppImage yt-link-linux.AppImage

      - name: Upload Packaged Application
        uses: actions/upload-artifact@v4
        with:
          name: yt-link-${{ matrix.os }}
          path: frontend/dist/*
          retention-days: 7
