name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Create Python virtual environment and install dependencies
        run: |
          cd service
          python -m venv venv
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./venv/Scripts/python.exe -m pip install -r requirements.txt
            ./venv/Scripts/python.exe -m pip install pyinstaller static-ffmpeg
          else
            ./venv/bin/python -m pip install -r requirements.txt
            ./venv/bin/python -m pip install pyinstaller static-ffmpeg
          fi
        shell: bash

      - name: Build Python Backend EXE (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          cd service
          # Find the actual paths to the executables provided by static-ffmpeg
          FFMPEG_PATH=$(./venv/Scripts/python.exe -c "import static_ffmpeg; print(static_ffmpeg.get_ffmpeg_path())")
          FFPROBE_PATH=$(./venv/Scripts/python.exe -c "import static_ffmpeg; print(static_ffmpeg.get_ffprobe_path())")
          
          echo "Found ffmpeg at: $FFMPEG_PATH"
          echo "Found ffprobe at: $FFPROBE_PATH"
          
          # Now, use these correct paths in PyInstaller
          ./venv/Scripts/python.exe -m PyInstaller --onefile --noconsole --clean \
            --add-binary "./venv/Scripts/yt-dlp.exe;." \
            --add-binary "$FFMPEG_PATH;." \
            --add-binary "$FFPROBE_PATH;." \
            app.py
        shell: bash

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build and Package Electron App
        run: npm run electron:build -- --publish always
        working-directory: ./frontend
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          IS_ELECTRON: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            frontend/dist/*.dmg
            frontend/dist/*.zip
            frontend/dist/*.exe
            frontend/dist/*.blockmap
